In [ ]:
# !pip install spark
# !pip install findspark

Requirement already satisfied: spark in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (0.3.2)
Requirement already satisfied: aiohttp>=3.10.5 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (3.13.3)
Requirement already satisfied: aiosqlite>=0.21.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (0.21.0)
Requirement already satisfied: docstring-parser>=0.17.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (0.17.0)
Requirement already satisfied: jinja2>=3.1.6 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (3.1.6)
Requirement already satisfied: json-repair>=0.52.4 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (0.58.5)
Requirement already satisfied: openai>=2.7.1 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (2.26.0)
Requirement already satisfied: pydantic<3.0,>=2.7 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (2.12.5)
Requirement already satisfied: starlette>=0.50.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (0.52.1)
Requirement already satisfied: typing-extensions>=4.15.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (4.15.0)
Requirement already satisfied: uvicorn>=0.38.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (0.40.0)
Requirement already satisfied: websockets>=15.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from spark) (16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from pydantic<3.0,>=2.7->spark) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from pydantic<3.0,>=2.7->spark) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from pydantic<3.0,>=2.7->spark) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from aiohttp>=3.10.5->spark) (1.22.0)
Requirement already satisfied: idna>=2.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp>=3.10.5->spark) (3.11)
Requirement already satisfied: MarkupSafe>=2.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from jinja2>=3.1.6->spark) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (0.13.0)
Requirement already satisfied: sniffio in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (1.3.1)
Requirement already satisfied: tqdm>4 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from openai>=2.7.1->spark) (4.67.3)
Requirement already satisfied: certifi in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai>=2.7.1->spark) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from httpx<1,>=0.23.0->openai>=2.7.1->spark) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=2.7.1->spark) (0.16.0)
Requirement already satisfied: click>=7.0 in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (from uvicorn>=0.38.0->spark) (8.3.1)
Requirement already satisfied: findspark in /home/linhnnh/miniconda3/envs/de/lib/python3.13/site-packages (2.0.1)

In [3]:
import findspark

findspark.init()
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import to_date
from pyspark.sql.types import DoubleType
import pandas as pd

In [6]:
spark = SparkSession.builder.appName("hw6").getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/03/10 06:39:20 WARN Utils: Your hostname, DESKTOP-KV2R5JB, resolves to a loopback address: 127.0.1.1; using 172.22.73.47 instead (on interface eth0)
26/03/10 06:39:20 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/10 06:39:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [7]:
spark

In [8]:
spark.version

'4.1.1'

In [9]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet

--2026-03-10 03:58:53--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 3.165.49.58, 3.165.49.150, 3.165.49.16, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|3.165.49.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71134255 (68M) [binary/octet-stream]
Saving to: ‘yellow_tripdata_2025-11.parquet’

yellow_tripdata_202 100%[===================>]  67.84M  25.9MB/s    in 2.6s

2026-03-10 03:58:56 (25.9 MB/s) - ‘yellow_tripdata_2025-11.parquet’ saved [71134255/71134255]

In [2]:
!wget 'https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv'

--2026-03-10 06:38:01--  https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 3.165.49.115, 3.165.49.150, 3.165.49.16, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|3.165.49.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12331 (12K) [text/csv]
Saving to: ‘taxi_zone_lookup.csv’

taxi_zone_lookup.cs 100%[===================>]  12.04K  --.-KB/s    in 0s

2026-03-10 06:38:01 (108 MB/s) - ‘taxi_zone_lookup.csv’ saved [12331/12331]

In [9]:
path = "./yellow_tripdata_2025-11.parquet"

df = spark.read.parquet(path, header=True, inferSchema=True)
# Repartition the DataFrame to 4 partitions
df_repartitioned = df.repartition(4)

# Save the repartitioned DataFrame to a directory in Parquet format
# The output will be a directory containing 4 parquet files (one for each partition)
output_path = "./parquet_files"
df_repartitioned.write.parquet(output_path, mode="overwrite")

In [10]:
df.show(5)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|Airport_fee|cbd_congestion_fee|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
|       7| 2025-11-01 00:13:25|  2025-11-01 00:13:25|              1|         1.68|         1|                 N|          43|         186|           1|       14.9|  0.0|    0.5|       1.5|         0.0|                  1.0|       22.15|                 2.5|        0.0|              0.75|
|       2| 2025-11-01 00:49:07|  2025-11-01 01:01:22|              1|         2.28|         1|                 N|         142|         237|           1|       14.2|  1.0|    0.5|      4.99|         0.0|                  1.0|       24.94|                 2.5|        0.0|              0.75|
|       1| 2025-11-01 00:07:19|  2025-11-01 00:20:41|              0|          2.7|         1|                 N|         163|         238|           1|       15.6| 4.25|    0.5|      4.27|         0.0|                  1.0|       25.62|                 2.5|        0.0|              0.75|
|       2| 2025-11-01 00:00:00|  2025-11-01 01:01:03|              3|        12.87|         1|                 N|         138|         261|           1|       66.7|  6.0|    0.5|       0.0|        6.94|                  1.0|       86.14|                 2.5|       1.75|              0.75|
|       1| 2025-11-01 00:18:50|  2025-11-01 00:49:32|              0|          8.4|         1|                 N|         138|          37|           2|       39.4| 7.75|    0.5|       0.0|         0.0|                  1.0|       48.65|                 0.0|       1.75|               0.0|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+
only showing top 5 rows

In [13]:
df.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)

In [16]:
df = df.withColumn("tpep_pickup_date_only", to_date("tpep_pickup_datetime"))
df = df.withColumn("tpep_dropoff_date_only", to_date("tpep_dropoff_datetime"))
df.show(5)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|Airport_fee|cbd_congestion_fee|tpep_pickup_date_only|tpep_dropoff_date_only|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+
|       7| 2025-11-01 00:13:25|  2025-11-01 00:13:25|              1|         1.68|         1|                 N|          43|         186|           1|       14.9|  0.0|    0.5|       1.5|         0.0|                  1.0|       22.15|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|
|       2| 2025-11-01 00:49:07|  2025-11-01 01:01:22|              1|         2.28|         1|                 N|         142|         237|           1|       14.2|  1.0|    0.5|      4.99|         0.0|                  1.0|       24.94|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|
|       1| 2025-11-01 00:07:19|  2025-11-01 00:20:41|              0|          2.7|         1|                 N|         163|         238|           1|       15.6| 4.25|    0.5|      4.27|         0.0|                  1.0|       25.62|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|
|       2| 2025-11-01 00:00:00|  2025-11-01 01:01:03|              3|        12.87|         1|                 N|         138|         261|           1|       66.7|  6.0|    0.5|       0.0|        6.94|                  1.0|       86.14|                 2.5|       1.75|              0.75|           2025-11-01|            2025-11-01|
|       1| 2025-11-01 00:18:50|  2025-11-01 00:49:32|              0|          8.4|         1|                 N|         138|          37|           2|       39.4| 7.75|    0.5|       0.0|         0.0|                  1.0|       48.65|                 0.0|       1.75|               0.0|           2025-11-01|            2025-11-01|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+
only showing top 5 rows

In [17]:
df.where("tpep_pickup_date_only = '2025-11-15'").count()

162604

In [31]:
df = df.withColumn("trip_duration", F.col("tpep_dropoff_datetime") - F.col("tpep_pickup_datetime"))
df.show(5)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|Airport_fee|cbd_congestion_fee|tpep_pickup_date_only|tpep_dropoff_date_only|           trip_time|trip_duration_seconds|       trip_duration|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+
|       7| 2025-11-01 00:13:25|  2025-11-01 00:13:25|              1|         1.68|         1|                 N|          43|         186|           1|       14.9|  0.0|    0.5|       1.5|         0.0|                  1.0|       22.15|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:00...| INTERVAL '0 00:00...|INTERVAL '0 00:00...|
|       2| 2025-11-01 00:49:07|  2025-11-01 01:01:22|              1|         2.28|         1|                 N|         142|         237|           1|       14.2|  1.0|    0.5|      4.99|         0.0|                  1.0|       24.94|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:12...| INTERVAL '0 00:12...|INTERVAL '0 00:12...|
|       1| 2025-11-01 00:07:19|  2025-11-01 00:20:41|              0|          2.7|         1|                 N|         163|         238|           1|       15.6| 4.25|    0.5|      4.27|         0.0|                  1.0|       25.62|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:13...| INTERVAL '0 00:13...|INTERVAL '0 00:13...|
|       2| 2025-11-01 00:00:00|  2025-11-01 01:01:03|              3|        12.87|         1|                 N|         138|         261|           1|       66.7|  6.0|    0.5|       0.0|        6.94|                  1.0|       86.14|                 2.5|       1.75|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 01:01...| INTERVAL '0 01:01...|INTERVAL '0 01:01...|
|       1| 2025-11-01 00:18:50|  2025-11-01 00:49:32|              0|          8.4|         1|                 N|         138|          37|           2|       39.4| 7.75|    0.5|       0.0|         0.0|                  1.0|       48.65|                 0.0|       1.75|               0.0|           2025-11-01|            2025-11-01|INTERVAL '0 00:30...| INTERVAL '0 00:30...|INTERVAL '0 00:30...|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+
only showing top 5 rows

In [32]:
df = df.withColumn(
    "trip_duration_hours",
    (F.col("trip_duration").cast("long") / 3600).cast(DoubleType()),
)
df.show(5)

26/03/10 04:38:59 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+-------------------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|Airport_fee|cbd_congestion_fee|tpep_pickup_date_only|tpep_dropoff_date_only|           trip_time|trip_duration_seconds|       trip_duration|trip_duration_hours|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+-------------------+
|       7| 2025-11-01 00:13:25|  2025-11-01 00:13:25|              1|         1.68|         1|                 N|          43|         186|           1|       14.9|  0.0|    0.5|       1.5|         0.0|                  1.0|       22.15|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:00...| INTERVAL '0 00:00...|INTERVAL '0 00:00...|                0.0|
|       2| 2025-11-01 00:49:07|  2025-11-01 01:01:22|              1|         2.28|         1|                 N|         142|         237|           1|       14.2|  1.0|    0.5|      4.99|         0.0|                  1.0|       24.94|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:12...| INTERVAL '0 00:12...|INTERVAL '0 00:12...|0.20416666666666666|
|       1| 2025-11-01 00:07:19|  2025-11-01 00:20:41|              0|          2.7|         1|                 N|         163|         238|           1|       15.6| 4.25|    0.5|      4.27|         0.0|                  1.0|       25.62|                 2.5|        0.0|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 00:13...| INTERVAL '0 00:13...|INTERVAL '0 00:13...|0.22277777777777777|
|       2| 2025-11-01 00:00:00|  2025-11-01 01:01:03|              3|        12.87|         1|                 N|         138|         261|           1|       66.7|  6.0|    0.5|       0.0|        6.94|                  1.0|       86.14|                 2.5|       1.75|              0.75|           2025-11-01|            2025-11-01|INTERVAL '0 01:01...| INTERVAL '0 01:01...|INTERVAL '0 01:01...|             1.0175|
|       1| 2025-11-01 00:18:50|  2025-11-01 00:49:32|              0|          8.4|         1|                 N|         138|          37|           2|       39.4| 7.75|    0.5|       0.0|         0.0|                  1.0|       48.65|                 0.0|       1.75|               0.0|           2025-11-01|            2025-11-01|INTERVAL '0 00:30...| INTERVAL '0 00:30...|INTERVAL '0 00:30...| 0.5116666666666667|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+---------------------+----------------------+--------------------+---------------------+--------------------+-------------------+
only showing top 5 rows

In [35]:
df.agg(F.max("trip_duration_hours")).collect()[0][0]

90.64666666666666

In [23]:
df.createOrReplaceTempView("trips")
df_pulocation = spark.sql("SELECT PULocationID, count(1) FROM trips GROUP BY PULocationID order by count(1)").toPandas()

In [29]:
df_pulocation.head(5)

   PULocationID  count(1)
0           105         1
1             5         1
2            84         1
3           187         3
4           204         4

In [19]:
taxi_zone = spark.read.csv("taxi_zone_lookup.csv", header=True, inferSchema=True).toPandas()
taxi_zone.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [30]:
taxi_zone[taxi_zone.LocationID == 105]

,LocationID,Borough,Zone,service_zone
104,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone